# Generated by Django 5.1.4 on 2024-12-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dosage', models.CharField(max_length=100)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.croptype')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_yield', models.FloatField()),
                ('potential_yield', models.FloatField()),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.croptype')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
    ]
