# Generated by Django 5.1.4 on 2024-12-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yielddata',
            options={'verbose_name_plural': 'Yield Data'},
        ),
        migrations.AlterField(
            model_name='croptype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
